import type { KubernetesObject } from "./mod.ts";
import { stringify } from "@std/yaml";

/**
 * Sink interface for emitted Kubernetes resources. A sink receives all resources that are passed to {@link Gin#emit},
 * but usually wants to filter out those that have the `parent` field in {@link KubernetesObject#gin} set, as those are
 * usually not actual Kubernetes resources and should not be applied to a cluster.
 */
export interface Sink {
  /**
   * Accepts a Kubernetes resource and processes it.
   *
   * @param resource - The Kubernetes resource to process.
   */
  accept<T extends KubernetesObject>(resource: T): Promise<void>;

  /**
   * Closes the sink, indicating no more resources will be sent.
   */
  close(): void;
}

/**
 * Outputs Kubernetes resources to stdout in YAML format. This is the default sink.
 */
export class StdoutSink implements Sink {
  keepGinMetadata: boolean;
  emitParents: boolean;

  constructor({ keepGinMetadata = false, emitParents = false } = {}) {
    this.keepGinMetadata = keepGinMetadata;
    this.emitParents = emitParents;
  }

  /**
   * Accepts a Kubernetes resource and outputs it to stdout in YAML format.
   *
   * @param resource - The Kubernetes resource to output.
   */
  accept<T extends KubernetesObject>(resource: T): Promise<void> {
    // We either emit all resources if emitParents is enabled, or only those that have a parent resource (i.e. they
    // have been generated by other resources) or ones that produced no children when processed.
    const doEmit = this.emitParents || resource.gin?.children === undefined;
    if (!doEmit) {
      return Promise.resolve();
    }

    const resourceCopy = { ...resource };

    if (!this.keepGinMetadata && resourceCopy.gin) {
      delete resourceCopy.gin;
    }

    console.log("---");
    console.log(stringify(resourceCopy, { indent: 2 }));

    return Promise.resolve();
  }

  /**
   * Closes the sink. No additional resources will be accepted after this call.
   */
  close(): void {
    // No specific action needed for stdout sink
  }
}
